/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright 2019-2020,2022-2023 Hewlett Packard Enterprise Development LP. All rights reserved. */

#ifndef SBL_SERDES_MAP_H
#define SBL_SERDES_MAP_H

#include "uapi/sbl_iface_constants.h"
#include "sbl_kconfig.h"
#ifndef __KERNEL__
#include <stdbool.h>
#endif /*  __KERNEL__ */

#ifdef __cplusplus
extern "C" {
#endif

struct serdes_info {
	// Autogenerated values
	int device;
	int sbus_ring;
	int rx_addr;
	int tx_lane_source;
	int rx_lane_source;
	bool txinv;
	bool rxinv;
};

struct port_info {
	// Autogenerated values
	int		rx_an_swizzle;
	int		tx_an_swizzle;
	struct serdes_info serdes[SBL_SERDES_LANES_PER_PORT];
};

struct sbl_switch_info {
	int	      num_ports;
	int	      num_serdes; // per port
	int	      num_sbus_rings;
	struct port_info ports[CONFIG_SBL_NUM_PORTS];
};

#include "sbl_serdes_map_autogen.h"

#ifdef __cplusplus
}
#endif
#endif // SBL_SERDES_MAP_H
