name: Check for SITF pre-merge completion

on: 
  pull_request:
    types: [review_requested, opened, synchronize, reopened]

jobs:
  sitf-pre-merge:
    uses: hpe/hpc-lonesshot-slingshot_bot/.github/workflows/sitf_pre_merge_status.yaml@master
    secrets: inherit
